// <auto-generated />
using System;
using CSV_reader.database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSV_reader.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241107142248_removingEmailVerificationCols")]
    partial class removingEmailVerificationCols
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSV_reader.Models.ClientDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CarExp")
                        .HasColumnType("float");

                    b.Property<double>("CarLLL")
                        .HasColumnType("float");

                    b.Property<int>("CarNums")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Excess")
                        .HasColumnType("float");

                    b.Property<double>("ExpPercentage")
                        .HasColumnType("float");

                    b.Property<int>("FCDaysCOI")
                        .HasColumnType("int");

                    b.Property<int>("FCDaysNonCOI")
                        .HasColumnType("int");

                    b.Property<double>("FCTO_COI")
                        .HasColumnType("float");

                    b.Property<double>("FCTO_NonCOI")
                        .HasColumnType("float");

                    b.Property<double>("FiveY_AD")
                        .HasColumnType("float");

                    b.Property<double>("FiveY_ADOS")
                        .HasColumnType("float");

                    b.Property<int>("FiveY_ClaimsClo")
                        .HasColumnType("int");

                    b.Property<int>("FiveY_ClaimsOpen")
                        .HasColumnType("int");

                    b.Property<double>("FiveY_FT")
                        .HasColumnType("float");

                    b.Property<double>("FiveY_FTOS")
                        .HasColumnType("float");

                    b.Property<int>("FiveY_RDaysCOI")
                        .HasColumnType("int");

                    b.Property<int>("FiveY_RDaysNonCOI")
                        .HasColumnType("int");

                    b.Property<double>("FiveY_TO_COI")
                        .HasColumnType("float");

                    b.Property<double>("FiveY_TO_NonCOI")
                        .HasColumnType("float");

                    b.Property<double>("FiveY_TPCH")
                        .HasColumnType("float");

                    b.Property<double>("FiveY_TPCHOS")
                        .HasColumnType("float");

                    b.Property<double>("FiveY_TPPD")
                        .HasColumnType("float");

                    b.Property<double>("FiveY_TPPDOS")
                        .HasColumnType("float");

                    b.Property<double>("FiveY_TPPI")
                        .HasColumnType("float");

                    b.Property<double>("FiveY_TPPIOS")
                        .HasColumnType("float");

                    b.Property<double>("FiveY_Total")
                        .HasColumnType("float");

                    b.Property<double>("FiveY_UT")
                        .HasColumnType("float");

                    b.Property<double>("FiveY_VYrs")
                        .HasColumnType("float");

                    b.Property<double>("HGVExp")
                        .HasColumnType("float");

                    b.Property<double>("HGVLLL")
                        .HasColumnType("float");

                    b.Property<int>("HGVNums")
                        .HasColumnType("int");

                    b.Property<double>("MinibusExp")
                        .HasColumnType("float");

                    b.Property<double>("MinibusLLL")
                        .HasColumnType("float");

                    b.Property<int>("MinibusNums")
                        .HasColumnType("int");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ThreeY_AD")
                        .HasColumnType("float");

                    b.Property<double>("ThreeY_ADOS")
                        .HasColumnType("float");

                    b.Property<int>("ThreeY_ClaimsClo")
                        .HasColumnType("int");

                    b.Property<int>("ThreeY_ClaimsOpen")
                        .HasColumnType("int");

                    b.Property<double>("ThreeY_FT")
                        .HasColumnType("float");

                    b.Property<double>("ThreeY_FTOS")
                        .HasColumnType("float");

                    b.Property<int>("ThreeY_RDaysCOI")
                        .HasColumnType("int");

                    b.Property<int>("ThreeY_RDaysNonCOI")
                        .HasColumnType("int");

                    b.Property<double>("ThreeY_TO_COI")
                        .HasColumnType("float");

                    b.Property<double>("ThreeY_TO_NonCOI")
                        .HasColumnType("float");

                    b.Property<double>("ThreeY_TPCH")
                        .HasColumnType("float");

                    b.Property<double>("ThreeY_TPCHOS")
                        .HasColumnType("float");

                    b.Property<double>("ThreeY_TPPD")
                        .HasColumnType("float");

                    b.Property<double>("ThreeY_TPPDOS")
                        .HasColumnType("float");

                    b.Property<double>("ThreeY_TPPI")
                        .HasColumnType("float");

                    b.Property<double>("ThreeY_TPPIOS")
                        .HasColumnType("float");

                    b.Property<double>("ThreeY_Total")
                        .HasColumnType("float");

                    b.Property<double>("ThreeY_UT")
                        .HasColumnType("float");

                    b.Property<double>("ThreeY_VYrs")
                        .HasColumnType("float");

                    b.Property<double>("VanExp")
                        .HasColumnType("float");

                    b.Property<double>("VanLLL")
                        .HasColumnType("float");

                    b.Property<int>("VanNums")
                        .HasColumnType("int");

                    b.Property<double>("Y1ADOS")
                        .HasColumnType("float");

                    b.Property<double>("Y1ADPaid")
                        .HasColumnType("float");

                    b.Property<int>("Y1ClaimsClosed")
                        .HasColumnType("int");

                    b.Property<int>("Y1ClaimsOpen")
                        .HasColumnType("int");

                    b.Property<double>("Y1FTOS")
                        .HasColumnType("float");

                    b.Property<double>("Y1FTPaid")
                        .HasColumnType("float");

                    b.Property<int>("Y1RentalDaysCOI")
                        .HasColumnType("int");

                    b.Property<int>("Y1RentalDaysNonCOI")
                        .HasColumnType("int");

                    b.Property<double>("Y1TO_COI")
                        .HasColumnType("float");

                    b.Property<double>("Y1TO_NonCOI")
                        .HasColumnType("float");

                    b.Property<double>("Y1TPCH")
                        .HasColumnType("float");

                    b.Property<double>("Y1TPCHOS")
                        .HasColumnType("float");

                    b.Property<double>("Y1TPPD")
                        .HasColumnType("float");

                    b.Property<double>("Y1TPPDOS")
                        .HasColumnType("float");

                    b.Property<double>("Y1TPPI")
                        .HasColumnType("float");

                    b.Property<double>("Y1TPPIOS")
                        .HasColumnType("float");

                    b.Property<double>("Y1Total")
                        .HasColumnType("float");

                    b.Property<double>("Y1UT")
                        .HasColumnType("float");

                    b.Property<double>("Y1VYrs")
                        .HasColumnType("float");

                    b.Property<double>("Y2ADOS")
                        .HasColumnType("float");

                    b.Property<double>("Y2ADPaid")
                        .HasColumnType("float");

                    b.Property<int>("Y2ClaimsClosed")
                        .HasColumnType("int");

                    b.Property<int>("Y2ClaimsOpen")
                        .HasColumnType("int");

                    b.Property<double>("Y2FTOS")
                        .HasColumnType("float");

                    b.Property<double>("Y2FTPaid")
                        .HasColumnType("float");

                    b.Property<int>("Y2RentalDaysCOI")
                        .HasColumnType("int");

                    b.Property<int>("Y2RentalDaysNonCOI")
                        .HasColumnType("int");

                    b.Property<double>("Y2TO_COI")
                        .HasColumnType("float");

                    b.Property<double>("Y2TO_NonCOI")
                        .HasColumnType("float");

                    b.Property<double>("Y2TPCH")
                        .HasColumnType("float");

                    b.Property<double>("Y2TPCHOS")
                        .HasColumnType("float");

                    b.Property<double>("Y2TPPD")
                        .HasColumnType("float");

                    b.Property<double>("Y2TPPDOS")
                        .HasColumnType("float");

                    b.Property<double>("Y2TPPI")
                        .HasColumnType("float");

                    b.Property<double>("Y2TPPIOS")
                        .HasColumnType("float");

                    b.Property<double>("Y2Total")
                        .HasColumnType("float");

                    b.Property<double>("Y2UT")
                        .HasColumnType("float");

                    b.Property<double>("Y2VYrs")
                        .HasColumnType("float");

                    b.Property<double>("Y3ADOS")
                        .HasColumnType("float");

                    b.Property<double>("Y3ADPaid")
                        .HasColumnType("float");

                    b.Property<int>("Y3ClaimsClosed")
                        .HasColumnType("int");

                    b.Property<int>("Y3ClaimsOpen")
                        .HasColumnType("int");

                    b.Property<double>("Y3FTOS")
                        .HasColumnType("float");

                    b.Property<double>("Y3FTPaid")
                        .HasColumnType("float");

                    b.Property<int>("Y3RentalDaysCOI")
                        .HasColumnType("int");

                    b.Property<int>("Y3RentalDaysNonCOI")
                        .HasColumnType("int");

                    b.Property<double>("Y3TO_COI")
                        .HasColumnType("float");

                    b.Property<double>("Y3TO_NonCOI")
                        .HasColumnType("float");

                    b.Property<double>("Y3TPCH")
                        .HasColumnType("float");

                    b.Property<double>("Y3TPCHOS")
                        .HasColumnType("float");

                    b.Property<double>("Y3TPPD")
                        .HasColumnType("float");

                    b.Property<double>("Y3TPPDOS")
                        .HasColumnType("float");

                    b.Property<double>("Y3TPPI")
                        .HasColumnType("float");

                    b.Property<double>("Y3TPPIOS")
                        .HasColumnType("float");

                    b.Property<double>("Y3Total")
                        .HasColumnType("float");

                    b.Property<double>("Y3UT")
                        .HasColumnType("float");

                    b.Property<double>("Y3VYrs")
                        .HasColumnType("float");

                    b.Property<double>("Y4ADOS")
                        .HasColumnType("float");

                    b.Property<double>("Y4ADPaid")
                        .HasColumnType("float");

                    b.Property<int>("Y4ClaimsClosed")
                        .HasColumnType("int");

                    b.Property<int>("Y4ClaimsOpen")
                        .HasColumnType("int");

                    b.Property<double>("Y4FTOS")
                        .HasColumnType("float");

                    b.Property<double>("Y4FTPaid")
                        .HasColumnType("float");

                    b.Property<int>("Y4RentalDaysCOI")
                        .HasColumnType("int");

                    b.Property<int>("Y4RentalDaysNonCOI")
                        .HasColumnType("int");

                    b.Property<double>("Y4TO_COI")
                        .HasColumnType("float");

                    b.Property<double>("Y4TO_NonCOI")
                        .HasColumnType("float");

                    b.Property<double>("Y4TPCH")
                        .HasColumnType("float");

                    b.Property<double>("Y4TPCHOS")
                        .HasColumnType("float");

                    b.Property<double>("Y4TPPD")
                        .HasColumnType("float");

                    b.Property<double>("Y4TPPDOS")
                        .HasColumnType("float");

                    b.Property<double>("Y4TPPI")
                        .HasColumnType("float");

                    b.Property<double>("Y4TPPIOS")
                        .HasColumnType("float");

                    b.Property<double>("Y4Total")
                        .HasColumnType("float");

                    b.Property<double>("Y4UT")
                        .HasColumnType("float");

                    b.Property<double>("Y4VYrs")
                        .HasColumnType("float");

                    b.Property<double>("Y5ADOS")
                        .HasColumnType("float");

                    b.Property<double>("Y5ADPaid")
                        .HasColumnType("float");

                    b.Property<int>("Y5ClaimsClosed")
                        .HasColumnType("int");

                    b.Property<int>("Y5ClaimsOpen")
                        .HasColumnType("int");

                    b.Property<double>("Y5FTOS")
                        .HasColumnType("float");

                    b.Property<double>("Y5FTPaid")
                        .HasColumnType("float");

                    b.Property<int>("Y5RentalDaysCOI")
                        .HasColumnType("int");

                    b.Property<int>("Y5RentalDaysNonCOI")
                        .HasColumnType("int");

                    b.Property<double>("Y5TO_COI")
                        .HasColumnType("float");

                    b.Property<double>("Y5TO_NonCOI")
                        .HasColumnType("float");

                    b.Property<double>("Y5TPCH")
                        .HasColumnType("float");

                    b.Property<double>("Y5TPCHOS")
                        .HasColumnType("float");

                    b.Property<double>("Y5TPPD")
                        .HasColumnType("float");

                    b.Property<double>("Y5TPPDOS")
                        .HasColumnType("float");

                    b.Property<double>("Y5TPPI")
                        .HasColumnType("float");

                    b.Property<double>("Y5TPPIOS")
                        .HasColumnType("float");

                    b.Property<double>("Y5Total")
                        .HasColumnType("float");

                    b.Property<double>("Y5UT")
                        .HasColumnType("float");

                    b.Property<double>("Y5VYrs")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ClientDetails");
                });

            modelBuilder.Entity("CSV_reader.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
