using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CSV_reader.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "ClientDetails",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    QuoteNumber = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ClientName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CoverType = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    StartDate = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EndDate = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Excess = table.Column<double>(type: "float", nullable: false),
                    CarNums = table.Column<int>(type: "int", nullable: false),
                    VanNums = table.Column<int>(type: "int", nullable: false),
                    MinibusNums = table.Column<int>(type: "int", nullable: false),
                    HGVNums = table.Column<int>(type: "int", nullable: false),
                    CarLLL = table.Column<double>(type: "float", nullable: false),
                    VanLLL = table.Column<double>(type: "float", nullable: false),
                    MinibusLLL = table.Column<double>(type: "float", nullable: false),
                    HGVLLL = table.Column<double>(type: "float", nullable: false),
                    CarExp = table.Column<double>(type: "float", nullable: false),
                    VanExp = table.Column<double>(type: "float", nullable: false),
                    MinibusExp = table.Column<double>(type: "float", nullable: false),
                    HGVExp = table.Column<double>(type: "float", nullable: false),
                    ExpPercentage = table.Column<double>(type: "float", nullable: false),
                    FCDaysCOI = table.Column<int>(type: "int", nullable: false),
                    FCDaysNonCOI = table.Column<int>(type: "int", nullable: false),
                    FCTO_COI = table.Column<double>(type: "float", nullable: false),
                    FCTO_NonCOI = table.Column<double>(type: "float", nullable: false),
                    Y1RentalDaysCOI = table.Column<int>(type: "int", nullable: false),
                    Y2RentalDaysCOI = table.Column<int>(type: "int", nullable: false),
                    Y3RentalDaysCOI = table.Column<int>(type: "int", nullable: false),
                    Y4RentalDaysCOI = table.Column<int>(type: "int", nullable: false),
                    Y5RentalDaysCOI = table.Column<int>(type: "int", nullable: false),
                    ThreeY_RDaysCOI = table.Column<int>(type: "int", nullable: false),
                    FiveY_RDaysCOI = table.Column<int>(type: "int", nullable: false),
                    Y1RentalDaysNonCOI = table.Column<int>(type: "int", nullable: false),
                    Y2RentalDaysNonCOI = table.Column<int>(type: "int", nullable: false),
                    Y3RentalDaysNonCOI = table.Column<int>(type: "int", nullable: false),
                    Y4RentalDaysNonCOI = table.Column<int>(type: "int", nullable: false),
                    Y5RentalDaysNonCOI = table.Column<int>(type: "int", nullable: false),
                    ThreeY_RDaysNonCOI = table.Column<int>(type: "int", nullable: false),
                    FiveY_RDaysNonCOI = table.Column<int>(type: "int", nullable: false),
                    Y1TO_COI = table.Column<double>(type: "float", nullable: false),
                    Y2TO_COI = table.Column<double>(type: "float", nullable: false),
                    Y3TO_COI = table.Column<double>(type: "float", nullable: false),
                    Y4TO_COI = table.Column<double>(type: "float", nullable: false),
                    Y5TO_COI = table.Column<double>(type: "float", nullable: false),
                    ThreeY_TO_COI = table.Column<double>(type: "float", nullable: false),
                    FiveY_TO_COI = table.Column<double>(type: "float", nullable: false),
                    Y1TO_NonCOI = table.Column<double>(type: "float", nullable: false),
                    Y2TO_NonCOI = table.Column<double>(type: "float", nullable: false),
                    Y3TO_NonCOI = table.Column<double>(type: "float", nullable: false),
                    Y4TO_NonCOI = table.Column<double>(type: "float", nullable: false),
                    Y5TO_NonCOI = table.Column<double>(type: "float", nullable: false),
                    ThreeY_TO_NonCOI = table.Column<double>(type: "float", nullable: false),
                    FiveY_TO_NonCOI = table.Column<double>(type: "float", nullable: false),
                    Y1UT = table.Column<double>(type: "float", nullable: false),
                    Y2UT = table.Column<double>(type: "float", nullable: false),
                    Y3UT = table.Column<double>(type: "float", nullable: false),
                    Y4UT = table.Column<double>(type: "float", nullable: false),
                    Y5UT = table.Column<double>(type: "float", nullable: false),
                    ThreeY_UT = table.Column<double>(type: "float", nullable: false),
                    FiveY_UT = table.Column<double>(type: "float", nullable: false),
                    Y1VYrs = table.Column<double>(type: "float", nullable: false),
                    Y2VYrs = table.Column<double>(type: "float", nullable: false),
                    Y3VYrs = table.Column<double>(type: "float", nullable: false),
                    Y4VYrs = table.Column<double>(type: "float", nullable: false),
                    Y5VYrs = table.Column<double>(type: "float", nullable: false),
                    ThreeY_VYrs = table.Column<double>(type: "float", nullable: false),
                    FiveY_VYrs = table.Column<double>(type: "float", nullable: false),
                    Y1ClaimsOpen = table.Column<int>(type: "int", nullable: false),
                    Y2ClaimsOpen = table.Column<int>(type: "int", nullable: false),
                    Y3ClaimsOpen = table.Column<int>(type: "int", nullable: false),
                    Y4ClaimsOpen = table.Column<int>(type: "int", nullable: false),
                    Y5ClaimsOpen = table.Column<int>(type: "int", nullable: false),
                    ThreeY_ClaimsOpen = table.Column<int>(type: "int", nullable: false),
                    FiveY_ClaimsOpen = table.Column<int>(type: "int", nullable: false),
                    Y1ClaimsClosed = table.Column<int>(type: "int", nullable: false),
                    Y2ClaimsClosed = table.Column<int>(type: "int", nullable: false),
                    Y3ClaimsClosed = table.Column<int>(type: "int", nullable: false),
                    Y4ClaimsClosed = table.Column<int>(type: "int", nullable: false),
                    Y5ClaimsClosed = table.Column<int>(type: "int", nullable: false),
                    ThreeY_ClaimsClo = table.Column<int>(type: "int", nullable: false),
                    FiveY_ClaimsClo = table.Column<int>(type: "int", nullable: false),
                    Y1ADPaid = table.Column<double>(type: "float", nullable: false),
                    Y2ADPaid = table.Column<double>(type: "float", nullable: false),
                    Y3ADPaid = table.Column<double>(type: "float", nullable: false),
                    Y4ADPaid = table.Column<double>(type: "float", nullable: false),
                    Y5ADPaid = table.Column<double>(type: "float", nullable: false),
                    ThreeY_AD = table.Column<double>(type: "float", nullable: false),
                    FiveY_AD = table.Column<double>(type: "float", nullable: false),
                    Y1FTPaid = table.Column<double>(type: "float", nullable: false),
                    Y2FTPaid = table.Column<double>(type: "float", nullable: false),
                    Y3FTPaid = table.Column<double>(type: "float", nullable: false),
                    Y4FTPaid = table.Column<double>(type: "float", nullable: false),
                    Y5FTPaid = table.Column<double>(type: "float", nullable: false),
                    ThreeY_FT = table.Column<double>(type: "float", nullable: false),
                    FiveY_FT = table.Column<double>(type: "float", nullable: false),
                    Y1TPPD = table.Column<double>(type: "float", nullable: false),
                    Y2TPPD = table.Column<double>(type: "float", nullable: false),
                    Y3TPPD = table.Column<double>(type: "float", nullable: false),
                    Y4TPPD = table.Column<double>(type: "float", nullable: false),
                    Y5TPPD = table.Column<double>(type: "float", nullable: false),
                    ThreeY_TPPD = table.Column<double>(type: "float", nullable: false),
                    FiveY_TPPD = table.Column<double>(type: "float", nullable: false),
                    Y1TPCH = table.Column<double>(type: "float", nullable: false),
                    Y2TPCH = table.Column<double>(type: "float", nullable: false),
                    Y3TPCH = table.Column<double>(type: "float", nullable: false),
                    Y4TPCH = table.Column<double>(type: "float", nullable: false),
                    Y5TPCH = table.Column<double>(type: "float", nullable: false),
                    ThreeY_TPCH = table.Column<double>(type: "float", nullable: false),
                    FiveY_TPCH = table.Column<double>(type: "float", nullable: false),
                    Y1TPPI = table.Column<double>(type: "float", nullable: false),
                    Y2TPPI = table.Column<double>(type: "float", nullable: false),
                    Y3TPPI = table.Column<double>(type: "float", nullable: false),
                    Y4TPPI = table.Column<double>(type: "float", nullable: false),
                    Y5TPPI = table.Column<double>(type: "float", nullable: false),
                    ThreeY_TPPI = table.Column<double>(type: "float", nullable: false),
                    FiveY_TPPI = table.Column<double>(type: "float", nullable: false),
                    Y1ADOS = table.Column<double>(type: "float", nullable: false),
                    Y2ADOS = table.Column<double>(type: "float", nullable: false),
                    Y3ADOS = table.Column<double>(type: "float", nullable: false),
                    Y4ADOS = table.Column<double>(type: "float", nullable: false),
                    Y5ADOS = table.Column<double>(type: "float", nullable: false),
                    ThreeY_ADOS = table.Column<double>(type: "float", nullable: false),
                    FiveY_ADOS = table.Column<double>(type: "float", nullable: false),
                    Y1FTOS = table.Column<double>(type: "float", nullable: false),
                    Y2FTOS = table.Column<double>(type: "float", nullable: false),
                    Y3FTOS = table.Column<double>(type: "float", nullable: false),
                    Y4FTOS = table.Column<double>(type: "float", nullable: false),
                    Y5FTOS = table.Column<double>(type: "float", nullable: false),
                    ThreeY_FTOS = table.Column<double>(type: "float", nullable: false),
                    FiveY_FTOS = table.Column<double>(type: "float", nullable: false),
                    Y1TPPDOS = table.Column<double>(type: "float", nullable: false),
                    Y2TPPDOS = table.Column<double>(type: "float", nullable: false),
                    Y3TPPDOS = table.Column<double>(type: "float", nullable: false),
                    Y4TPPDOS = table.Column<double>(type: "float", nullable: false),
                    Y5TPPDOS = table.Column<double>(type: "float", nullable: false),
                    ThreeY_TPPDOS = table.Column<double>(type: "float", nullable: false),
                    FiveY_TPPDOS = table.Column<double>(type: "float", nullable: false),
                    Y1TPCHOS = table.Column<double>(type: "float", nullable: false),
                    Y2TPCHOS = table.Column<double>(type: "float", nullable: false),
                    Y3TPCHOS = table.Column<double>(type: "float", nullable: false),
                    Y4TPCHOS = table.Column<double>(type: "float", nullable: false),
                    Y5TPCHOS = table.Column<double>(type: "float", nullable: false),
                    ThreeY_TPCHOS = table.Column<double>(type: "float", nullable: false),
                    FiveY_TPCHOS = table.Column<double>(type: "float", nullable: false),
                    Y1TPPIOS = table.Column<double>(type: "float", nullable: false),
                    Y2TPPIOS = table.Column<double>(type: "float", nullable: false),
                    Y3TPPIOS = table.Column<double>(type: "float", nullable: false),
                    Y4TPPIOS = table.Column<double>(type: "float", nullable: false),
                    Y5TPPIOS = table.Column<double>(type: "float", nullable: false),
                    ThreeY_TPPIOS = table.Column<double>(type: "float", nullable: false),
                    FiveY_TPPIOS = table.Column<double>(type: "float", nullable: false),
                    Y1Total = table.Column<double>(type: "float", nullable: false),
                    Y2Total = table.Column<double>(type: "float", nullable: false),
                    Y3Total = table.Column<double>(type: "float", nullable: false),
                    Y4Total = table.Column<double>(type: "float", nullable: false),
                    Y5Total = table.Column<double>(type: "float", nullable: false),
                    ThreeY_Total = table.Column<double>(type: "float", nullable: false),
                    FiveY_Total = table.Column<double>(type: "float", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ClientDetails", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "ClientDetails");
        }
    }
}
